### ISSUE TITLE
AlexIILLib should be auto-downloaded if possible

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/BetterLoadingScreen#2]

**Comment by RAnders00** [comment]
A alternative may be #3

**Comment by AlexIIL** [comment]
#3 is closed, however for all those who don't use the curse client (which includes me as I use linux), this would be helpful

**Comment by RAnders00** [comment]
An alternate way would be a soft warning that AlexIILLib is missing (via dependencies in the @Mod() annotation). But since I never got to do 1.8 with Forge, you could prove me wrong that such does not exist anymore. If the dependencies are missing, a nice message in the minecraft window should appear and notify the user of a missing mod. The only mod I know that does auto-downloading is CodeChickenCore by chickenbones. It downloads CodeChickenLib automatically into the /mods/1.7.10/ folder.

**Comment by AlexIIL** [comment]
Closing this as (for now) I don't have a stable platform for automatic downloading from (CurseForge would fit this, except that i don't auto-upload yet)
