### ISSUE TITLE
Doesn't Work With Splash Animation Mod.

### ISSUE THREAD

**Issue by theshadowake** [AlexIIL/BetterLoadingScreen#55]
It would be fantastic if this mod could work with:

https://www.curseforge.com/minecraft/mc-mods/splashanimation

Using both together would allow much more professional looking packs.

(I use your mod in all the Awakening modpacks and would love to be able to also add a splash screen).

**Comment by AlexIIL** [comment]
A little while ago I think I refused to add compatibility because our mods are two different, and I would have preferred to add general support for animation in CLS instead. However I've looked into this a bit more and it turns out it might be possible to make it work as-is, just by rendering the splash animation mod before my own (but after showing the mojang logo).

**Comment by AlexIIL** [comment]
Ok, this should be implemented + working in 1.4.1 (https://www.curseforge.com/minecraft/mc-mods/better-loading-screen/files/2783190)

**Comment by theshadowake** [comment]
Wow thank you so much for the quick fix. <3

**Comment by AlexIIL** [comment]
Yeah it turns out SplashAnimation was designed well which made this easier :)
